### ISSUE TITLE
Tilastollisen vertailukohdan laskeminen

### ISSUE THREAD

**Issue by mkoske** [Tommytronic/Scatter-R#1]
Artikkelissa sanottiin, että tilastollista vertailukohtaa (engl. statistical baseline) laskettaessa algorimi ajetaan ~30 kertaa ja niista lasketaan tämä vertailukohta. Pitäisikö olla kovakoodattuna vai konfiguroitavissa tämä?

**Comment by jmpaon** [comment]
Jos siitä ei ole vaivaa niin se voisi olla optionaalinen argumentti funktioon oletusarvolla 30.

**Comment by mkoske** [comment]
Se täytyy olla sitten myös siinä GUI:ssa

**Comment by mkoske** [comment]
Laitettu parametriksi baseline-funktiolle. Suljen.
