### ISSUE TITLE
Keräysvektorin pituus väärä

### ISSUE THREAD

**Issue by mkoske** [Tommytronic/Scatter-R#11]
Keräysvektorin pituus iris-datalla on yhden vähemän kuin pitäisi (iris-data, 149, po. 150)

**Comment by Tommytronic** [comment]
Onko tietoa miksi? Helppo korjata?

**Comment by mkoske** [comment]
Vastasinkin jo Flowdockiin, mutta vastaan vielä tänne. Eli todennäköisesti tiedän, mistä johtuu enkä usko että on vaikea korjata.
