### ISSUE TITLE
Siirrä Scatter omaan ympäristöönsä

### ISSUE THREAD

**Issue by mkoske** [Tommytronic/Scatter-R#15]
Ettei sotke globaalia ympäristöä

**Comment by jmpaon** [comment]
Riittää kun sulkee algoritmin käyttämät funktiot ylemmän funktion sisälle. Ympäristöä ei tarvita.

**Comment by mkoske** [comment]
Minusta olisi hyvä, että pystyisi käyttämään niitä muitakin funktioita. Jos ne sulkee tuollain, onko se mahdollista?

**Comment by jmpaon** [comment]
@mkoske Ei kai se ole siinä tapauksessa mahdollista.. eli sitten kai environment on hyvä ratkaisu.

**Comment by mkoske** [comment]
Namespace-jutuilla sai tämän hoidettua.
