### ISSUE TITLE
Dokumentointi: Technical documentation

### ISSUE THREAD

**Issue by Tommytronic** [Tommytronic/Scatter-R#20]
- Englanniksi
- Tietovirtakaavio
- Selitys ohjelman toiminnoista (esim. mitä taustalla tapahtuu kun...)
- Selitys algoritmin toiminnoista ja parametreista
- Miten GUI ja algoritmi pelaa yhteen

**Comment by Tommytronic** [comment]
@mkoske @jmpaon

**Comment by mkoske** [comment]
Ilmeisesti ei tarvita.
